name: Trigger auto deployment for spring-rest-container-new

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ AzureConAppsTesting ]
    paths:
    - '**'
    - '.github/workflows/spring-rest-container-new-AutoDeployTrigger-ed5ed233-c96f-4605-b20a-c7879e951e06.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: springbootcontainers.azurecr.io
          username: ${{ secrets.SPRINGRESTCONTAINERNEW_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGRESTCONTAINERNEW_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: springbootcontainers.azurecr.io/welcome:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGRESTCONTAINERNEW_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n spring-rest-container-new -g app-dev-rg --server springbootcontainers.azurecr.io --username  ${{ secrets.SPRINGRESTCONTAINERNEW_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGRESTCONTAINERNEW_REGISTRY_PASSWORD }}
            az containerapp update -n spring-rest-container-new -g app-dev-rg --image springbootcontainers.azurecr.io/welcome:${{ github.sha }}
