name: Trigger auto deployment for spring-rest-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ AzureConAppsTesting ]
    paths:
    - '**'
    - '.github/workflows/spring-rest-container-AutoDeployTrigger-43b33063-95e7-48dc-8f90-10045a702fce.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
        
      #- name: Checkout to the branch
      #  uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: springbootcontainers.azurecr.io
          username: ${{ secrets.SPRINGRESTCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGRESTCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: springbootcontainers.azurecr.io/welcome:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGRESTCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n spring-rest-container-new -g app-dev-rg --server springbootcontainers.azurecr.io --username  ${{ secrets.SPRINGRESTCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGRESTCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n spring-rest-container-new -g app-dev-rg --image springbootcontainers.azurecr.io/welcome:${{ github.sha }}
