name: Trigger auto deployment for spring-rest-template-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/spring-rest-template-container-AutoDeployTrigger-7412a534-8d4f-4d44-84ac-bb511ca946eb.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: springbootcontainers.azurecr.io
          username: ${{ secrets.SPRINGRESTTEMPLATECONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGRESTTEMPLATECONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: springbootcontainers.azurecr.io/spring-rest-template-container:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGRESTTEMPLATECONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n spring-rest-template-container -g app-dev-rg --server springbootcontainers.azurecr.io --username  ${{ secrets.SPRINGRESTTEMPLATECONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGRESTTEMPLATECONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n spring-rest-template-container -g app-dev-rg --image springbootcontainers.azurecr.io/spring-rest-template-container:${{ github.sha }}
